### ISSUE TITLE
Connection Error - Couldn't connect to ethereum node on AWS at http://xx.xxx.xx.xxx:8545

### ISSUE THREAD

**Issue by kirtisanchana** [ethereum/wiki#445]
We setup ethereum node on _AWS Ubuntu Server 16.04 LTS (HVM) EC2 instance_ and configured it in the standard way before launching the geth console using the below command:
`
sudo geth --identity "EthereumMain" --datadir ~/.ethereum_private/ --networkid "123" --verbosity 3 --nodiscover --rpcapi "admin,db,eth,debug,miner,net,shh,txpool,personal,web3" --rpccorsdomain "*" --rpc --port "30301" --rpcport "8545" --rpcaddr "0.0.0.0"  --nat "any" console 2>> ~/fm-ethchain/fm-ethchain.log
`

(Basically we tried to incorporate all the suggestions we found on various forums and websites to solve the problem!! )

Now, when we try to connect to this node from lambda function using the web3:
`var web3 = new Web3(
new Web3.providers.HttpProvider('http://xx.xxx.xx.xxx:8545')
);
`

We keep getting the following error:

> CONNECTION ERROR: Couldn't connect to node http://xx.xxx.xx.xxx:8545 (where xx.xxx.xx.xxx is the public IP address of the EC2 instance).

Can somebody please specify what is the mistake or what is it that we are missing?

**Comment by PHPJourney** [comment]
me too,

**Comment by karthiknvlr** [comment]
I have the same setup in AWS EC2 Ubuntu instance. I have installed geth 1.6.5 with go 1.7 
And these are the commands which I used to connect to the blockchain.

geth --datadir "etherum/test" --networkid 1234 --port 30303 --rpc --rpcport 30303 --rpcaddr="0.0.0.0" --rpcapi "web" --rpccorsdomain "*" console
```nodejs
const Web3 = require('web3');
const web3 = new Web3(new Web3.providers.HttpProvider("http://xx.xxx.xxx.xxx:8545"));
```

where xx.xxx.xxx.xxx is my AWS EC2 instance public ip 
check either you have allowed port 8545 in security policy or not in ec2 instance dashboard.

**Comment by kirtisanchana** [comment]
Hi @karthiknvlr Thank you for responding! We are trying the same way, only exceptions being installing go and --rpcapi "web" parameter, which we incorporated but still no luck!

Anything else that you think might help?

**Comment by karthiknvlr** [comment]
Hi @kirtisanchana can you able to peer local system node with you blockchain node?
Check either you have enabled port 8545 in EC2 Instance or not?
And try without adding nodiscover option while getting into your geth console.

**Comment by kirtisanchana** [comment]
Hi @karthiknvlr - Yes, 8545 port is enabled in EC2 instance (sorry for missing to specify that in my previous post). And, we did try without the nodiscover option (when we tried to replicate your command) and also I believe --rpcport has to be 8545 and not 30303 in your command?

By peering local system node with blockchain node you mean connecting or telnet from one node to the other? If yes, then I am able to do that. Or do you mean adding the IP address of the other node as the peer in the geth console?

**Comment by karthiknvlr** [comment]
Hi @kirtisanchana Sorry rpcport is 8545. 
try admin.addpeer("enode:id of blockchain:public ip of AWS instance:30303")
If the result was true and for admin.peer if you can see the result then it needs to connect.
And if possible send me the output when you are executing the nodejs script.

**Comment by kirtisanchana** [comment]
Hi @karthiknvlr - Thank you for the explanation. Can you please confirm if I need to do admin.addpeer("enode://xxxxxxxxxxxxxxxxxxx@public_ip_of_mainnode:30301") is what I need to run on the main node? (where xxxxxxx is the enode id of the main node)
I did the above and the result was true and for admin.peers it is returning [] - Not sure if I am missing something here.

I am trying to connect to the main node using Lambda function of AWS and please find below the output when executing the script:

> Error: CONNECTION ERROR: Couldn't connect to node http://ec2-34-203-213-46.compute-1.amazonaws.com:8545.    at Object.InvalidConnection (/var/task/node_modules/web3/lib/web3/errors.js:28:16)    at HttpProvider.send (/var/task/node_modules/web3/lib/web3/httpprovider.js:79:22)    at RequestManager.send (/var/task/node_modules/web3/lib/web3/requestmanager.js:58:32)    at Eth.get (/var/task/node_modules/web3/lib/web3/property.js:106:62)    at exports.handler.e (/var/task/index.js:22:32)
--

**Comment by karthiknvlr** [comment]
Hi @kirtisanchana  

- You need to run admin.peer command from your local system, to make your local system as part of your block chain(NODE).

- After that run net.peering - you will get the result as 1. If not peering was not done and there was an issue connecting with you AWS instance.

- If this happens then I am sure you can access your AWS blockchain instance using nodejs and web3.

**Comment by kirtisanchana** [comment]
Hi @karthiknvlr 
Like I mentioned in my previous post, we are trying to connect to the main node using AWS lambda function and so we don't have an option of installing geth on that. I believe we can't run admin.addPeer command on it without installing geth. So, any other way around?

**Comment by karthiknvlr** [comment]
Hi @kirtisanchana  
Without installing geth node how you had created accounts and how you are doing mining.
In ethereum, geth console is like terminal which will control all the operation which we need to perform in the blockchain.
After starting geth console  using 
```terminal 
sudo geth --identity "EthereumMain" --datadir ~/.ethereum_private/ --networkid "123" --verbosity 3 --nodiscover --rpcapi "admin,db,eth,debug,miner,net,shh,txpool,personal,web3" --rpccorsdomain "*" --rpc --port "30301" --rpcport "8545" --rpcaddr "0.0.0.0" --nat "any" console 2>> ~/fm-ethchain/fm-ethchain.log
```
```terminal
$netstat -plnt
````
Run the above command in seperate terminal of AWS instance and check whethere port 8545 is listening to binding ip, you will get output similar to the below one.
```terminal
Proto  Recv-Q  Send-Q   Local Address    Foreign Address   State       PID/Program name
tcp6     0     0            :::8545          :::*          LISTEN      4202/geth
```

If you not getting this output, then you are blockchain was not running in your EC2 instance.
If you are getting output similar to this then you can able to connect to your blockchain instance from your AWS lambda function.

**Comment by kirtisanchana** [comment]
Hi @karthiknvlr 
Thank you for the patience in answering my queries. I didn't say that geth is not installed on the nodes. It is not installed on the a separate instance of AWS which is used to connect to the node using lambda function. Hope it is clear!

On running netstat -plnt on a separate terminal of AWS, yes it is giving the above output but still I am   not able to connect to the blockchain instance using the AWS lambda function.

**Comment by santoshphatangare** [comment]
In geth flag --rpcaddr provide private IP of server.
And 
var web3 = new Web3( new Web3.providers.HttpProvider('http://xx.xxx.xx.xxx:8545') );
In above line use public IP.
It will work.

**Comment by rhlsthrm** [comment]
@kirtisanchana did you ever get this working? I am having the same issue. It appears as if the solutions on the thread here are not addressing the issue.

**Comment by pfrank8** [comment]
Make sure you pass --nat "any", that was it for me!

**Comment by gulbinas** [comment]
same error: lambda running nodejs/web3 can't connect to geth instance running on EC2

```Error: CONNECTION ERROR: Couldn't connect to node http://54.194.138.161:8545.
    at Object.InvalidConnection (/var/task/node_modules/web3/lib/web3/errors.js:28:16)
    at HttpProvider.send (/var/task/node_modules/web3/lib/web3/httpprovider.js:83:22)
    at Provider.send (/var/task/node_modules/truffle-contract/contract.js:19:31)
    at RequestManager.send (/var/task/node_modules/truffle-contract/node_modules/web3/lib/web3/requestmanager.js:58:32)
    at Eth.get [as coinbase] (/var/task/node_modules/truffle-contract/node_modules/web3/lib/web3/property.js:107:62)
    at /var/task/src/registry/handler.js:25:44
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)```

```
    "web3": "^0.19.0",
    "truffle-contract": "^2.0.5"
```

**Comment by avatar-lavventura** [comment]
ICMP port is closed by default on AWS instances. You need to enable it in a security group.

Here is more detailed information: https://stackoverflow.com/questions/21981796/cannot-ping-aws-ec2-instance

TCP and UDP in inbound rules should be accessible by anywhere:[![enter image description here][1]][1]


  [1]: https://i.stack.imgur.com/dkVY0.png

**Comment by jlagarden** [comment]
for some reason geth doesn't bind to ```0.0.0.0:8545``` and ```:::8545``` when started with ```--rpcaddr "0.0.0.0"``` but to ```:::8454``` only, which is an IPv6 Address. 

That means that geth will be reachable when connecting to port 8454 using IPv6 or form localhost but not from the outside when using an IPv4 address.

 compare the output of the following commands
```
sudo netstat -tulpn | grep 'ssh'
``` 
outputs 
```
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1178/sshd       
tcp6       0      0 :::22                   :::*                    LISTEN      1178/sshd   
```
sshd daemon is listening on 0.0.0.0:22 and :::22, but
 ```
sudo netstat -tulpn | grep 'geth'
``` 
outputs 
```
tcp6       0      0 :::30303                :::*                    LISTEN      1862/geth       
tcp6       0      0 :::8545                 :::*                    LISTEN      1862/geth       
udp6       0      0 :::30303                :::*                                1862/geth   
```
geth is only listening on :::8454 and :::30303

**Comment by Ollemesh** [comment]
I had the same trouble and spend a long time to find the reason.
web3.js has XMLHttpRequest (npm module) as a dependency. This module writes some temp files when sending a request.
(see here:  [xmlhttprequest source][1], line 477 )

**It means your NodeJs process needs to write files permission**


  [1]: https://github.com/driverdan/node-XMLHttpRequest/blob/master/lib/XMLHttpRequest.js

**Comment by bwysocki** [comment]
True, the full error is like that :

{ Error: EROFS: read-only file system, open '.node-xmlhttprequest-sync-1'
at Error (native)
at Object.fs.openSync (fs.js:641:18)
at Object.fs.writeFileSync (fs.js:1347:33)
at send (/var/task/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:477:10)
at HttpProvider.send (/var/task/node_modules/web3/lib/web3/httpprovider.js:91:13)
at RequestManager.send (/var/task/node_modules/web3/lib/web3/requestmanager.js:58:32)
at Eth.send [as getTransactionCount] (/var/task/node_modules/web3/lib/web3/method.js:145:58)
at prepareAddWalletSerializedTx (/var/task/index.js:24:37)
at isWhitelistedAsync.then (/var/task/index.js:73:36)
at tryCatcher (/var/task/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/var/task/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/var/task/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromise0 (/var/task/node_modules/bluebird/js/release/promise.js:614:10)
at Promise._settlePromises (/var/task/node_modules/bluebird/js/release/promise.js:693:18)
at Promise._fulfill (/var/task/node_modules/bluebird/js/release/promise.js:638:18)
at /var/task/node_modules/bluebird/js/release/nodeback.js:42:21
errno: -30,
code: 'EROFS',
syscall: 'open',
path: '.node-xmlhttprequest-sync-1' }

**Comment by elvece** [comment]
@Ollemesh @bwysocki How could I go about enabling write permissions for nodejs processes if I wanted to do this in an after-install.sh script?

**Comment by bmatthewshea** [comment]
@avatar-lavventura :    
Happened to see your post above just now. Are you nuts?!?
You should NEVER allow **all** udp/tcp ports for public. NEVER. EVER. >> Don't do it. <<
THIS IS TERRIBLE ADVICE if anyone reads the above reply. DON'T DO IT.
By allowing ALL, you have also allowed the public to talk to your privileged ports as well.
By the lack of replies to this misinformation I am guessing the rest of you do not have a clue, either?

Oh and BTW ping has NOTHING to do with UDP or TCP. You are quite wrong on all counts and have given information in your post that could potentially allow someone to get hacked (and hacked quite badly).

**Comment by avatar-lavventura** [comment]
@bmatthewshea I have removed it, sorry I got messed up. Should I consider to open ICMP port?
Please see:
https://stackoverflow.com/a/43230366/2402577

**Comment by bmatthewshea** [comment]
Cool. TY
If you want to just ping your instance? 
Yes allow echo/ICMP. IIRC there is a specific entry under ICMP in AWS to allow pings.
And no need to allow everyone/public - just pick 'my ip' as the allowed IP. Since ping is usually just for testing the network - by you. Unless you really want people to discover your instance by simply pinging (I don't recommend that).
(And yes: PING has nothing to do with TCP or UDP - strictly an ICMP packet/proto).

**Comment by avatar-lavventura** [comment]
@bmatthewshea ;
 In order to add an ethereum node as a peer => its IP and PORT is given.
`admin.addPeer(enodeID@[IP]:30303)`

> In order to add that peer,  TCP (30303) would it be enough open? even if I cannot ping to IP?

**Comment by bmatthewshea** [comment]
Ping doesn't mean a machine or vm exists.
It's just an echo reuest - if the node has echo request off (most do), you willnot get a ping back. Do not depend on ping to determine if server is 'alive'. Telnet to it's Peer port instead to determine if connections are happening.

`telnet (node IP) 30303`

If it opens a connection just CTRL-C out. You know it's alive/talking, then.

**Comment by GeeeCoin** [comment]
@santoshphatangare is giving private IP to --rpcaddr similar to passing --nat "any"? I have a problem connecting to my ec2 hosted Geth node from my Node server with web3. And do you mean the private IP of the geth client or Node server? Thanks!

**Comment by krishnasaiiiit** [comment]
Hi Team,
We installed ethereum on aws manually. We have a RPC end point to connect using web3 HTTP provider. 
We implemented a lamda function which can connect to RPC endpoint. But we are getting errors while doing it.
Please find the below error to solve. Could you please help us on this
![image](https://user-images.githubusercontent.com/5790905/38086431-ecbcb85a-3371-11e8-80dd-3b9358e798d0.png)

**Comment by bmatthewshea** [comment]
@krishnasaiiiit 
Sure looks like port simply isn't answering a request?
Maybe dumb questions, but have to ask -
- EC2 instance? Have you allowed port via AWS security/ports? ( 8545 ) You can telnet to it from allowed AWS ip(s)?
- If port open, have you tried troubleshooting port by trying to send 'manual' web3 requests?
- If so (or not), is there an IAM you use under this? Does the IAM have proper security to access instance/port via Lamda, etc? I seem to recall needing to do this in past when using lambda code..

Sorry if this is redundant info for you. All I can think of.. hope something helps.

**Comment by WarrEagle** [comment]
You might want to attach an EC2FullAccess role to your Lambda function.

**Comment by sumitpatel93** [comment]
[my gcp screenshot](https://prnt.sc/jfoa2h)

**Comment by mseijas** [comment]
Still having the same issue - has anyone been able to figure out a solution? I have tried all posted answers and still keep running into the same issue.

**Comment by jamesray1** [comment]
Just looked at this now; the reason this was closed is [here](https://github.com/ethereum/wiki/wiki#issues-and-pull-requests).

**Comment by JadenGu** [comment]
> I am able to resolve the issue .. not it works like a charm !!



> NodeJs process needs to write files permission . Ollemesh `s answer solve my problem. I use sudo to start the js, then solve the prolbem.

Doesn't work for me..

**Comment by JadenGu** [comment]
> I am able to resolve the issue .. not it works like a charm !!

Any details? encountering the same issue these days. Thanks a lot.
